### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DaveAtkinsonXMOS**
Modified README.md to point out that this repo is now obselete.

### CODE REVIEW

**Comment by DaveAtkinsonXMOS** [comment]
I think we should delete the script file from the archived repo. Who's with me?

**Comment by BrennanGit** [comment]
I got no problem with it. Like talked about, usually we archive to preserve urls/functionality whilst noting that there will be no more updates. This allows historical builds to not be affected but in this case, the repo in standalone so there is no need for historical builds. If it makes it even clearer that these scripts no longer work then go for it. 

@mbanth what do you think?

**Comment by BrennanGit** [comment]
I'll be happy to archive these two repos once these PRs are merged, assuming there are no objections.

**Review by mbanth — APPROVED** [review]
The Read Me text change is fine.  I'm also happy with deleting the script.

**Comment by DaveAtkinsonXMOS** [comment]
Repo ready to be archived.

**Pull request merged**
